# Generated by Django 6.0.2 on 2026-03-12 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_embalagem', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('unidade', 'Unidade'), ('g', 'Grama')], max_length=10)),
                ('custo_unitario', models.DecimalField(decimal_places=5, editable=False, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='InsumoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_embalagem', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=10)),
                ('preco_por_unidade', models.DecimalField(decimal_places=5, max_digits=10)),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('alteracao', 'Alteração')], max_length=10)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Histórico de insumo',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
