# Generated by Django 6.0.2 on 2026-02-04 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo_medida', models.CharField(choices=[('P', 'Peso (gramas)'), ('U', 'Unidade')], max_length=1)),
                ('quantidade_base', models.DecimalField(decimal_places=3, help_text='Quantidade descrita na embalagem (g ou und)', max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do produto', max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=6, editable=False, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor pago pelo insumo na data', max_digits=10)),
                ('quantidade_base', models.DecimalField(decimal_places=3, help_text='Quantidade base do insumo (ex: gramas ou unidades)', max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=6, help_text='Custo por grama ou por unidade', max_digits=12)),
                ('data_referencia', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, help_text='Ex: reajuste fornecedor, troca de marca, correção', max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Histórico de Insumo',
                'verbose_name_plural': 'Histórico de Insumos',
                'ordering': ['-data_referencia'],
                'indexes': [models.Index(fields=['insumo', 'data_referencia'], name='insumos_his_insumo__2d8d82_idx')],
            },
        ),
    ]
