# Generated by Django 6.0.2 on 2026-03-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='preco',
            new_name='preco_custo',
        ),
        migrations.RenameField(
            model_name='insumohistorico',
            old_name='preco',
            new_name='preco_custo',
        ),
    ]
