# Generated by Django 6.0.2 on 2026-03-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_rename_preco_insumo_preco_custo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumohistorico',
            old_name='preco_por_unidade',
            new_name='custo_unitario',
        ),
    ]
